# Generated by Django 4.2.1 on 2023-06-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNumber', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=10)),
                ('Address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('TaskName', models.CharField(max_length=200)),
                ('Date', models.DateField(default=None)),
                ('Time', models.TimeField(default=None)),
                ('Assign', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taskApp.user')),
            ],
        ),
    ]
